name: Deploy MiCard Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies (if any)
        run: pip install --upgrade pip

      - name: Generate embedded index.html
        run: |
          python generate_micrad_index.py

      - name: Build Docker image
        run: docker build -t micard-backend .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/micard-backend:latest

      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/micard-backend:latest
            docker stop micard-backend || true
            docker rm micard-backend || true
            docker run -d --restart always \
              -p 80:3000 \
              --env-file /path/to/env/file \
              --name micard-backend \
              ghcr.io/${{ github.repository }}/micard-backend:latest